version: '3.11'

services:
  backend:
    build:
      dockerfile: Dockerfile_backend
      args:
        - GIT_BRANCH=${BRANCH}
    command: poetry run uvicorn main:app --host 0.0.0.0
    ports:
      - "${PORT_BACKEND}:8000"
    environment:
      - BRANCH=${BRANCH}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      args:
        - GIT_BRANCH=${BRANCH}
    ports:
        - "${PORT_FRONTEND}:3000"
    environment:
      - BRANCH=${BRANCH}
