FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y git
ARG GIT_BRANCH
RUN git clone -b $GIT_BRANCH https://github.com/s1lver29/wallet-save.git /app

RUN pip install poetry==1.7.1

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app/src/

RUN poetry install --without dev && rm -rf $POETRY_CACHE_DIR

WORKDIR /app/src/backend